name: Fork Sync

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: CloudNStoyan/fork-sync@v1.2
        with:
          base: lts
          head: lts
          auto_merge: false
